//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Manage_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Manage_Client()
        {
            this.App_Manage_Order = new HashSet<App_Manage_Order>();
        }
    
        public int cust_code { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string Cust_Mobile { get; set; }
        public string Cust_email { get; set; }
        public int cust_status { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> update_entry_date { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Loginr_Mode { get; set; }
        public string Last_Login_time { get; set; }
        public Nullable<System.DateTime> Last_Login_Date { get; set; }
        public string Country_Code { get; set; }
        public string Password { get; set; }
        public string platform { get; set; }
        public string Device_id { get; set; }
        public string token_id { get; set; }
        public string Social_media_id { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Manage_Order> App_Manage_Order { get; set; }
    }
}
