//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Manage_Order
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> delivery_boy_id { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string status { get; set; }
        public string Order_delivery_status { get; set; }
        public Nullable<decimal> Tot_Bill_Amt { get; set; }
        public Nullable<decimal> Tot_Discount { get; set; }
        public Nullable<decimal> Tot_Tax { get; set; }
        public Nullable<decimal> Refund_Amt { get; set; }
        public Nullable<decimal> Recd_Amt { get; set; }
        public string Estimate_time { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Update_Author_Id { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string update_entry_date { get; set; }
        public Nullable<int> fin_id { get; set; }
        public string Remark { get; set; }
        public string flag_delivery_boy { get; set; }
        public Nullable<decimal> Delivery_Charges { get; set; }
        public Nullable<int> OTP_no { get; set; }
        public string session_id { get; set; }
        public string Promo_code { get; set; }
        public string ORDER_TIME { get; set; }
        public Nullable<decimal> Tot_Bill_Recv_Vendor { get; set; }
        public Nullable<decimal> Tot_Bill_Bal_Vendor { get; set; }
        public string Payment_Transaction_Status { get; set; }
        public Nullable<System.DateTime> Delivered_Time { get; set; }
    }
}
