//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class s_foodEntities1 : DbContext
    {
        public s_foodEntities1()
            : base("name=s_foodEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uni_Restaurant> uni_Restaurant { get; set; }
        public virtual DbSet<UNI_CITY> UNI_CITY { get; set; }
        public virtual DbSet<uni_state> uni_state { get; set; }
        public virtual DbSet<uni_area> uni_area { get; set; }
        public virtual DbSet<App_Manage_Order> App_Manage_Order { get; set; }
        public virtual DbSet<Uni_Product> Uni_Product { get; set; }
        public virtual DbSet<UNI_CATEGORY> UNI_CATEGORY { get; set; }
    }
}
