//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_CATEGORY
    {
        public int Category_id { get; set; }
        public string Category_Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<int> Update_Author_Id { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<System.DateTime> update_entry_date { get; set; }
        public string Image1 { get; set; }
    }
}
