//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class uni_Restaurant
    {
        public int res_id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Contact_person_name { get; set; }
        public string Address { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> State_id { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public string Primary_Phone { get; set; }
        public string Secondary_Phone { get; set; }
        public string Primary_Email_Id { get; set; }
        public string Secondary_Email_Id { get; set; }
        public string URL { get; set; }
        public string Rating { get; set; }
        public string Rest_Dur { get; set; }
        public Nullable<decimal> Rest_Per { get; set; }
        public string Res_Status { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> update_entry_date { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<int> update_author_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> Verify_By { get; set; }
        public string verify_rem { get; set; }
        public Nullable<int> fin_id { get; set; }
        public string restaurant_Logo { get; set; }
        public string user_id { get; set; }
        public string pass1 { get; set; }
        public string confirm_pass { get; set; }
        public Nullable<decimal> Commission_Given { get; set; }
        public string Dispatch_Provider { get; set; }
        public string Trending_Brand { get; set; }
        public string res_display_img { get; set; }
        public string Rest_open_time { get; set; }
        public string Rest_Open_mes { get; set; }
        public string Rest_close_time { get; set; }
        public string Rest_close_mes { get; set; }
        public string Category_Name { get; set; }
        public Nullable<int> Discount { get; set; }
    }
}
