//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quenchhunger
{
    using System;
    using System.Collections.Generic;
    
    public partial class uni_area
    {
        public int Area_id { get; set; }
        public string Area_name { get; set; }
        public string status { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> update_author_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> update_entry_date { get; set; }
    }
}
